"""
3D LUT (.cube) export for color grade transfer.

Generates a 3D lookup table by sampling the color transform across
the full RGB color space. The resulting .cube file can be imported
into DaVinci Resolve, Premiere Pro, Photoshop, Lightroom, etc.
"""

import numpy as np
import cv2
import os
from typing import Callable, Optional


def _generate_identity_lattice(size: int = 33) -> np.ndarray:
    """
    Generate an identity 3D LUT lattice.
    Creates a grid of all RGB combinations at the given resolution.

    Args:
        size: Number of samples per channel (33 is standard).

    Returns:
        Array of shape (size^3, 3) with normalized RGB values [0, 1].
    """
    steps = np.linspace(0, 1, size)
    # Create meshgrid (R varies fastest, then G, then B)
    r, g, b = np.meshgrid(steps, steps, steps, indexing='ij')
    lattice = np.stack([r.ravel(), g.ravel(), b.ravel()], axis=-1)
    return lattice.astype(np.float64)


def generate_lut_from_transfer(source_img: np.ndarray,
                               reference_img: np.ndarray,
                               transfer_fn: Callable,
                               postprocess_fn: Callable,
                               lut_size: int = 33,
                               strength: float = 0.8,
                               preserve_lum: bool = True) -> np.ndarray:
    """
    Generate a 3D LUT by applying the color transfer to a lattice
    of all possible colors.

    The approach:
        1. Create a synthetic image containing all LUT lattice colors
        2. Run it through the same transfer pipeline
        3. Read back the transformed colors as the LUT output

    Args:
        source_img: Source image (RGB uint8) — used to define the transform.
        reference_img: Reference image (RGB uint8) — color target.
        transfer_fn: Color transfer function (e.g., mkl_transfer).
        postprocess_fn: Postprocessing function.
        lut_size: LUT resolution per channel (33 is standard).
        strength: Transfer strength.
        preserve_lum: Whether to preserve luminance.

    Returns:
        LUT array of shape (lut_size^3, 3) with output RGB values [0, 1].
    """
    from core.preprocess import load_and_convert, bgr_to_lab

    # Step 1: Compute the transfer on the actual source/reference pair
    # to establish the color mapping parameters
    source_lab = load_and_convert(source_img, size=(256, 256))
    reference_lab = load_and_convert(reference_img, size=(256, 256))

    # Step 2: Create a synthetic image from the LUT lattice
    n_colors = lut_size ** 3
    side = int(np.ceil(np.sqrt(n_colors)))

    lattice = _generate_identity_lattice(lut_size)

    # Pad to fill square image
    padded = np.zeros((side * side, 3), dtype=np.float64)
    padded[:n_colors] = lattice
    lattice_img = (padded.reshape(side, side, 3) * 255).astype(np.uint8)

    # Convert lattice image to BGR then LAB
    lattice_bgr = cv2.cvtColor(lattice_img, cv2.COLOR_RGB2BGR)
    lattice_lab = cv2.cvtColor(lattice_bgr, cv2.COLOR_BGR2LAB).astype(np.float32)

    # Step 3: Apply the same transfer to the lattice image
    transferred_lab = transfer_fn(lattice_lab, reference_lab)

    # Step 4: Postprocess
    result_bgr = postprocess_fn(
        source_lab=lattice_lab,
        transferred_lab=transferred_lab,
        strength=strength,
        preserve_lum=preserve_lum,
        sharpen=False,
        apply_denoise=False,
    )

    # Step 5: Convert back to RGB and extract LUT values
    result_rgb = cv2.cvtColor(result_bgr, cv2.COLOR_BGR2RGB)
    result_flat = result_rgb.reshape(-1, 3)[:n_colors]
    lut_output = result_flat.astype(np.float64) / 255.0

    return lut_output


def export_cube_lut(lut_data: np.ndarray,
                    filepath: str,
                    lut_size: int = 33,
                    title: str = "ColorGradeTransfer") -> str:
    """
    Export a 3D LUT as an Adobe/Resolve .cube file.

    The .cube format is the industry standard for 3D LUTs, supported by:
    - DaVinci Resolve
    - Adobe Premiere Pro
    - Adobe Photoshop
    - Adobe Lightroom
    - Final Cut Pro
    - Capture One

    Args:
        lut_data: Array of shape (lut_size^3, 3) with RGB values [0, 1].
        filepath: Output .cube file path.
        lut_size: LUT resolution per channel.
        title: LUT title embedded in the file.

    Returns:
        Absolute path to the saved .cube file.
    """
    os.makedirs(os.path.dirname(filepath) if os.path.dirname(filepath) else '.', exist_ok=True)

    with open(filepath, 'w') as f:
        f.write(f"TITLE \"{title}\"\n")
        f.write(f"# Generated by ColorGradeTransfer\n")
        f.write(f"# https://github.com/colorgradetransfer\n")
        f.write(f"\n")
        f.write(f"DOMAIN_MIN 0.0 0.0 0.0\n")
        f.write(f"DOMAIN_MAX 1.0 1.0 1.0\n")
        f.write(f"LUT_3D_SIZE {lut_size}\n")
        f.write(f"\n")

        for i in range(len(lut_data)):
            r, g, b = lut_data[i]
            f.write(f"{r:.6f} {g:.6f} {b:.6f}\n")

    return os.path.abspath(filepath)


def apply_cube_lut(image_rgb: np.ndarray,
                   lut_data: np.ndarray,
                   lut_size: int = 33) -> np.ndarray:
    """
    Apply a 3D LUT to an image using trilinear interpolation.

    Args:
        image_rgb: Input image as RGB uint8.
        lut_data: LUT array of shape (lut_size^3, 3) with RGB [0, 1].
        lut_size: LUT resolution per channel.

    Returns:
        Color-graded image as RGB uint8.
    """
    h, w = image_rgb.shape[:2]
    img_norm = image_rgb.astype(np.float64) / 255.0

    # Scale to LUT indices
    img_scaled = img_norm * (lut_size - 1)

    # Floor and ceil indices
    idx_low = np.floor(img_scaled).astype(int)
    idx_high = np.minimum(idx_low + 1, lut_size - 1)

    # Fractional parts for interpolation
    frac = img_scaled - idx_low

    # Reshape LUT for 3D indexing
    lut_3d = lut_data.reshape(lut_size, lut_size, lut_size, 3)

    # Trilinear interpolation
    r0, g0, b0 = idx_low[:, :, 0], idx_low[:, :, 1], idx_low[:, :, 2]
    r1, g1, b1 = idx_high[:, :, 0], idx_high[:, :, 1], idx_high[:, :, 2]
    fr, fg, fb = frac[:, :, 0:1], frac[:, :, 1:2], frac[:, :, 2:3]

    # 8 corners of the cube
    c000 = lut_3d[r0, g0, b0]
    c001 = lut_3d[r0, g0, b1]
    c010 = lut_3d[r0, g1, b0]
    c011 = lut_3d[r0, g1, b1]
    c100 = lut_3d[r1, g0, b0]
    c101 = lut_3d[r1, g0, b1]
    c110 = lut_3d[r1, g1, b0]
    c111 = lut_3d[r1, g1, b1]

    # Interpolate
    c00 = c000 * (1 - fb) + c001 * fb
    c01 = c010 * (1 - fb) + c011 * fb
    c10 = c100 * (1 - fb) + c101 * fb
    c11 = c110 * (1 - fb) + c111 * fb

    c0 = c00 * (1 - fg) + c01 * fg
    c1 = c10 * (1 - fg) + c11 * fg

    result = c0 * (1 - fr) + c1 * fr

    return np.clip(result * 255, 0, 255).astype(np.uint8)
